# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Checkout engine"
        uses: actions/checkout@v2
        with:
          repository: compsoc-edinburgh/bi-engine
          path: bi-engine
          
      - name: "Checkout content"
        uses: actions/checkout@v2
        with:
          repository: penalosa/betterinformatics
          path: betterinformatics

      - name: Pull content into engine & build
        working-directory: bi-engine
        run: |
          make frombi
          echo "Data"
          ls src/data
          npm i
          npm run export
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./__sapper__/export
  
